version: 2.1
jobs:
  build-and-patch:
    docker:
    # specify the version
      - image: circleci/node:latest

    steps:
      - run: git clone https://github.com/snyk/snyk
      - run: cd snyk
      - run: npm install --save-dev pkg
      - run: npm install
      - run: npx pkg
      - run: git describe --tags > VERSION
      - persist_to_workspace:
          root: .
          paths:
            - dist/*
            - VERSION

  publish-github-release:
    docker:
      - image: gcr.io/snyk-technical-services/cicd-github
        auth:
          username: _json_key
          password: $GCLOUD_GCR_SNYK_TS_READER
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: | 
            VERSION=$(cat VERSION)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} dist/

workflows:
  version: 2.1
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-patch
  build-and-patch:
    jobs:
      - build-and-patch:
          filters:
            branches:
              only:
                  - master
      - publish-github-release:
          requires:
            - build-and-patch
          filters:
            branches:
              only:
                - master