version: 2.1
jobs:
  build-and-patch:
    docker:
    # specify the version
      - image: circleci/node:latest

    steps:
      - checkout
      - run: git config --global user.email "antoine@snyk.io"
      - run: git config --global user.name "Snyk Tech Services"
      - run: git clone https://github.com/snyk/snyk
      - run: cd snyk && git describe --tags > VERSION
      - run: cd snyk && TAG=$(git describe --tags) && git checkout ${TAG}
      - run: cd snyk && npm install --save-dev pkg --legacy-peer-deps
      - run: cd snyk && npm install
      #- run: cd snyk && git apply ../longformprojectname.patch
      - run: cd snyk && ../applyChangesInFiles.sh
      - run: cd snyk && npm run build
      - run: cd snyk && ../updateVersionInPackageFile.sh
      - run: cd snyk && npx pkg .
      - persist_to_workspace:
          root: .
          paths:
            - snyk/snyk-*
            - snyk/VERSION

  publish-github-release:
    docker:
      - image: gcr.io/snyk-technical-services/cicd-github
        auth:
          username: _json_key
          password: $GCLOUD_GCR_SNYK_TS_READER
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: ls && ls snyk/  
      - run:
          name: "Publish Release on GitHub"
          command: | 
            VERSION=$(cat snyk/VERSION)
            ghr -t ${GH_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} snyk/

workflows:
  version: 2.1
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-patch
      - publish-github-release:
           context: SNYK
           requires:
            - build-and-patch
  build-and-patch:
    jobs:
      - build-and-patch:
          filters:
            branches:
              only:
                  - master
      - publish-github-release:
          context: SNYK
          requires:
            - build-and-patch
          filters:
            branches:
              only:
                - master